Ensure that `USER` is set when building packages.
We've run across a build which fails if USER is not set in the
environment, `astyle`, so we'll explicitly set it for consistency with
what a normal interactive session would have.

I've diff `env` in the container environment and one in a normal
interactive oneother and this is the only difference.

diff --git a/.slackbuilds-library/resources/buildpkg b/.slackbuilds-library/resources/buildpkg
--- a/.slackbuilds-library/resources/buildpkg
+++ b/.slackbuilds-library/resources/buildpkg
@@ -5,6 +5,12 @@ set -e
 entrypoint="/bin/bash"
 arg=""
 
+# docker does not set `USER` normally, but typically this would be set in a
+# normal environment when building slackbuilds manually, so we'll set it for
+# consistency. We've seen at least one build, `astyle`, which fails without
+# `USER` being set.
+env_vars="-e USER=root -e LOGNAME=root"
+
 if [ -z "$build_arch" ] ; then
   echo "arch?"
   exit 1
@@ -62,12 +68,12 @@ if [ "$action" = "build" ] || [ "$action" = "rebuild" ]; then
   {
     if [ "$build_package" = "all" ] ; then
       # shellcheck disable=SC2086
-      docker run --rm --cap-add SYS_ADMIN $loopback_devices --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "git config --global --add safe.directory /var/lib/slackrepo/SBo/slackbuilds && slackrepo $action"
+      docker run --rm --cap-add SYS_ADMIN $loopback_devices $env_vars --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "git config --global --add safe.directory /var/lib/slackrepo/SBo/slackbuilds && slackrepo $action"
     else
       echo "# buildpkg $build_arch $build_package"
       echo '```'
       # shellcheck disable=SC2086
-      docker run --rm --cap-add SYS_ADMIN $loopback_devices --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "git config --global --add safe.directory /var/lib/slackrepo/SBo/slackbuilds && slackrepo $action $build_package"
+      docker run --rm --cap-add SYS_ADMIN $loopback_devices $env_vars --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$logs":/var/log/slackrepo -v "$git":"$slackrepo/slackbuilds" "$slackrepo_image"-$shortarch $arg -l -c "git config --global --add safe.directory /var/lib/slackrepo/SBo/slackbuilds && slackrepo $action $build_package"
     fi
     echo '```'
   } 2>&1 | sed 's/slackrepo/repo/g' | sed '/mount: /d' | sed "/^:-)/s/^:-) \(.*\) (-:$/✅ \1 ✅/" | sed "/^:-(/s/^:-( \(.*\) )-:$/⛔️ \1 ⛔️/" | tee ../build_results
@@ -135,7 +141,8 @@ EOF
     {
       echo "# sbopkglint $build_arch $build_package"
       echo '```'
-      docker run --rm --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$(dirname "$(pwd)")/helper/:/tmp/helper" aclemons/sbo-maintainer-tools:latest-$slackversion-$shortarch $arg -l -c "/tmp/helper/run_lint" || true
+      # shellcheck disable=SC2086
+      docker run --rm $env_vars --platform "$platform" --entrypoint "$entrypoint" -v "$sbo":"$slackrepo" -v "$(dirname "$(pwd)")/helper/:/tmp/helper" aclemons/sbo-maintainer-tools:latest-$slackversion-$shortarch $arg -l -c "/tmp/helper/run_lint" || true
       rm -rf ../helper
       echo '```'
     } 2>&1 | sed 's/slackrepo/repo/g' | sed "/All tests passed/s/^\(.*\)$/✅ \1 ✅/" | sed "/\!\!\!/s/^\(.*\)$/⛔️ \1 ⛔️/" | tee ../lint_results
